---
title: "Gladiator_gene_graph"
author: "Ping Hu"
date: "2022-11-16"
output: html_document
---
###prepare data -- matrix for correlation analysis
```{r 1setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(ggplot2)
library(ggplot2)
library(ggpubr)
library(plotly)
library(tidyverse)
#filename ="gladiator_match_species_asfs.txt"
#outname ="RA7asfs"
filename ="gladiator.CorData.Genus.txt"
outname ="RA6asfs"

A<-read.table(filename, sep="\t", header=TRUE)
d <- dim(A);
B=A[1:d[1], 2:d[2]]
ZZ=as.numeric(min(B[B>0&!is.na(B)]))/100
xx=log10(B+ZZ)
rownames(xx)=A[,1]
library("Hmisc")
rCOR=rcorr(as.matrix(xx), type="spearman")
write.csv(rCOR$P,file=paste0(outname,'.corP.csv'),sep=",",row.names=colnames(xx), col.names = colnames(xx))
write.csv(rCOR$r,file=paste0(outname,'.corR.csv'),sep=",",row.names=colnames(xx), col.names = colnames(xx))
# ++++++++++++++++++++++++++++
# flattenCorrMatrix
# ++++++++++++++++++++++++++++
# cormat : matrix of the correlation coefficients
# pmat : matrix of the correlation p-values
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
  )
}

ff<-flattenCorrMatrix(rCOR$r, rCOR$P)
write.csv(ff,file=paste0(outname,'.corFlat.csv'))
```


```{r 2graph echo=FALSE}
library(corrplot)
res <- cor(xx)
round(res, 2)
testRes = cor.mtest(xx, conf.level = 0.95)
tiff(filename = paste0(outname,".Cor.tiff"), width = 2860, height = 2860, res=300)
corrplot.mixed(res, p.mat = testRes$p, rect.hc = NA,sig.level=0.05, insig = "blank",  order="original",diag = "u",  upper = "ellipse", lower.col = "black",  number.cex = 0.7, tl.pos = "lt", tl.col = "black")
dev.off()

```
